services:
  db:
    image: postgres:15.6
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  rabbitmq:
    image: rabbitmq:3.13.1-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      
  redis:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    
  worker:
    build: .
    command: celery -A forum worker -l info
    restart: always
    depends_on:
      - redis
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=forum.settings.prod

  django:
    build: .
    restart: always
    container_name: django
    command: ["/app/wait-for-it.sh", "db:5432", "--", "sh", "-c",
              "python manage.py migrate &&
              uwsgi --ini ./config/uwsgi/uwsgi.ini"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=forum.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
      - rabbitmq
      - worker

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./forum/:/forum
    ports:
      - "80:80"